version: "3"

services:
  database: 
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=flaskblog
    ports:
      - '5432:5432'
    volumes:
      - flaskblog-db:/var/lib/postgresql/data

volumes:
  flaskblog-db:
    driver: local
