version: "3"

services:
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
    - "1080:1080"
    - "1025:1025"
  database: 
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=flaskblog
    ports:
      - '5432:5432'
    volumes:
      - flaskblog-db:/var/lib/postgresql/data

volumes:
  flaskblog-db:
    driver: local
